// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstructionMsgBook.proto

#include "InstructionMsgBook.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_InstructionMsgBook_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_InstructionMsgBook_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_InstructionMsg;
}  // namespace protobuf_InstructionMsgBook_2eproto
namespace tutorial {
class InstructionMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InstructionMsg>
      _instance;
} _InstructionMsg_default_instance_;
class InstructionMsgBookDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InstructionMsgBook>
      _instance;
} _InstructionMsgBook_default_instance_;
}  // namespace tutorial
namespace protobuf_InstructionMsgBook_2eproto {
static void InitDefaultsInstructionMsg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tutorial::_InstructionMsg_default_instance_;
    new (ptr) ::tutorial::InstructionMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::InstructionMsg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_InstructionMsg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInstructionMsg}, {}};

static void InitDefaultsInstructionMsgBook() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tutorial::_InstructionMsgBook_default_instance_;
    new (ptr) ::tutorial::InstructionMsgBook();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::InstructionMsgBook::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_InstructionMsgBook =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsInstructionMsgBook}, {
      &protobuf_InstructionMsgBook_2eproto::scc_info_InstructionMsg.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_InstructionMsg.base);
  ::google::protobuf::internal::InitSCC(&scc_info_InstructionMsgBook.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::InstructionMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::InstructionMsg, inst_name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::InstructionMsgBook, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::InstructionMsgBook, inst_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tutorial::InstructionMsg)},
  { 6, -1, sizeof(::tutorial::InstructionMsgBook)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tutorial::_InstructionMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tutorial::_InstructionMsgBook_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "InstructionMsgBook.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030InstructionMsgBook.proto\022\010tutorial\"#\n\016"
      "InstructionMsg\022\021\n\tinst_name\030\001 \001(\t\"<\n\022Ins"
      "tructionMsgBook\022&\n\004inst\030\001 \003(\0132\030.tutorial"
      ".InstructionMsgb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 143);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "InstructionMsgBook.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_InstructionMsgBook_2eproto
namespace tutorial {

// ===================================================================

void InstructionMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InstructionMsg::kInstNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InstructionMsg::InstructionMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_InstructionMsgBook_2eproto::scc_info_InstructionMsg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.InstructionMsg)
}
InstructionMsg::InstructionMsg(const InstructionMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  inst_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.inst_name().size() > 0) {
    inst_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inst_name_);
  }
  // @@protoc_insertion_point(copy_constructor:tutorial.InstructionMsg)
}

void InstructionMsg::SharedCtor() {
  inst_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

InstructionMsg::~InstructionMsg() {
  // @@protoc_insertion_point(destructor:tutorial.InstructionMsg)
  SharedDtor();
}

void InstructionMsg::SharedDtor() {
  inst_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void InstructionMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InstructionMsg::descriptor() {
  ::protobuf_InstructionMsgBook_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_InstructionMsgBook_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InstructionMsg& InstructionMsg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_InstructionMsgBook_2eproto::scc_info_InstructionMsg.base);
  return *internal_default_instance();
}


void InstructionMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.InstructionMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  inst_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool InstructionMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tutorial.InstructionMsg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string inst_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_inst_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->inst_name().data(), static_cast<int>(this->inst_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.InstructionMsg.inst_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.InstructionMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.InstructionMsg)
  return false;
#undef DO_
}

void InstructionMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.InstructionMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string inst_name = 1;
  if (this->inst_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->inst_name().data(), static_cast<int>(this->inst_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.InstructionMsg.inst_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->inst_name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tutorial.InstructionMsg)
}

::google::protobuf::uint8* InstructionMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tutorial.InstructionMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string inst_name = 1;
  if (this->inst_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->inst_name().data(), static_cast<int>(this->inst_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.InstructionMsg.inst_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->inst_name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tutorial.InstructionMsg)
  return target;
}

size_t InstructionMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.InstructionMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string inst_name = 1;
  if (this->inst_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->inst_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InstructionMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tutorial.InstructionMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const InstructionMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InstructionMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tutorial.InstructionMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tutorial.InstructionMsg)
    MergeFrom(*source);
  }
}

void InstructionMsg::MergeFrom(const InstructionMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.InstructionMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inst_name().size() > 0) {

    inst_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inst_name_);
  }
}

void InstructionMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tutorial.InstructionMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InstructionMsg::CopyFrom(const InstructionMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.InstructionMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstructionMsg::IsInitialized() const {
  return true;
}

void InstructionMsg::Swap(InstructionMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InstructionMsg::InternalSwap(InstructionMsg* other) {
  using std::swap;
  inst_name_.Swap(&other->inst_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InstructionMsg::GetMetadata() const {
  protobuf_InstructionMsgBook_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_InstructionMsgBook_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void InstructionMsgBook::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InstructionMsgBook::kInstFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InstructionMsgBook::InstructionMsgBook()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_InstructionMsgBook_2eproto::scc_info_InstructionMsgBook.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.InstructionMsgBook)
}
InstructionMsgBook::InstructionMsgBook(const InstructionMsgBook& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      inst_(from.inst_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tutorial.InstructionMsgBook)
}

void InstructionMsgBook::SharedCtor() {
}

InstructionMsgBook::~InstructionMsgBook() {
  // @@protoc_insertion_point(destructor:tutorial.InstructionMsgBook)
  SharedDtor();
}

void InstructionMsgBook::SharedDtor() {
}

void InstructionMsgBook::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InstructionMsgBook::descriptor() {
  ::protobuf_InstructionMsgBook_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_InstructionMsgBook_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InstructionMsgBook& InstructionMsgBook::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_InstructionMsgBook_2eproto::scc_info_InstructionMsgBook.base);
  return *internal_default_instance();
}


void InstructionMsgBook::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.InstructionMsgBook)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  inst_.Clear();
  _internal_metadata_.Clear();
}

bool InstructionMsgBook::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tutorial.InstructionMsgBook)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tutorial.InstructionMsg inst = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_inst()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.InstructionMsgBook)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.InstructionMsgBook)
  return false;
#undef DO_
}

void InstructionMsgBook::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.InstructionMsgBook)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tutorial.InstructionMsg inst = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->inst_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->inst(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tutorial.InstructionMsgBook)
}

::google::protobuf::uint8* InstructionMsgBook::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tutorial.InstructionMsgBook)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tutorial.InstructionMsg inst = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->inst_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->inst(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tutorial.InstructionMsgBook)
  return target;
}

size_t InstructionMsgBook::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.InstructionMsgBook)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .tutorial.InstructionMsg inst = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->inst_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->inst(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InstructionMsgBook::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tutorial.InstructionMsgBook)
  GOOGLE_DCHECK_NE(&from, this);
  const InstructionMsgBook* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InstructionMsgBook>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tutorial.InstructionMsgBook)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tutorial.InstructionMsgBook)
    MergeFrom(*source);
  }
}

void InstructionMsgBook::MergeFrom(const InstructionMsgBook& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.InstructionMsgBook)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  inst_.MergeFrom(from.inst_);
}

void InstructionMsgBook::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tutorial.InstructionMsgBook)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InstructionMsgBook::CopyFrom(const InstructionMsgBook& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.InstructionMsgBook)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstructionMsgBook::IsInitialized() const {
  return true;
}

void InstructionMsgBook::Swap(InstructionMsgBook* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InstructionMsgBook::InternalSwap(InstructionMsgBook* other) {
  using std::swap;
  CastToBase(&inst_)->InternalSwap(CastToBase(&other->inst_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InstructionMsgBook::GetMetadata() const {
  protobuf_InstructionMsgBook_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_InstructionMsgBook_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tutorial
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tutorial::InstructionMsg* Arena::CreateMaybeMessage< ::tutorial::InstructionMsg >(Arena* arena) {
  return Arena::CreateInternal< ::tutorial::InstructionMsg >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tutorial::InstructionMsgBook* Arena::CreateMaybeMessage< ::tutorial::InstructionMsgBook >(Arena* arena) {
  return Arena::CreateInternal< ::tutorial::InstructionMsgBook >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
